language: node_js
sudo: required
addons:
    chrome: stable
node_js:
  - 6
os: linux
cache:
  yarn: true
install:
  - yarn install
script:
  - npm run lint
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js