sudo: false
language: node_js
node_js: 
  - 6
addons:
  chrome: stable
cache:
  yarn: true
install:
  - yarn install
script:
  - npm run lint
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js