sudo: false
language: node_js
node_js: stable
before_install:
- export CHROME_BIN=chromium-browser
script:
  - npm run lint
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
