sudo: required
addons:
  chrome: stable
language: node_js
node_js: 
  - 8
cache:
  yarn: true
branches:
  only:
  - master
  - dev
script:
  - npm run lint
  - npm run unit
after_success:
  - cat ./test/unit/coverage/lcov.info | coveralls